/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_oppo_demo_JNIFunction */

#ifndef _Included_com_example_oppo_demo_JNIFunction
#define _Included_com_example_oppo_demo_JNIFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_oppo_demo_JNIFunction
 * Method:    test
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_oppo_1demo_JNIFunction_test
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
