/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_oppo_demo_JNIFunction */

#ifndef _Included_com_example_oppo_demo_JNIFunction
#define _Included_com_example_oppo_demo_JNIFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_oppo_demo_JNIFunction
 * Method:    init
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_oppo_1demo_JNIFunction_init
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_example_oppo_demo_JNIFunction
 * Method:    run
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_oppo_1demo_JNIFunction_run
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
